title:              Quska Blog
email:              qusrhkdwls45@gmail.com
description:        공부 ㄱ
author:             Quska
baseurl:            ""
url:                "https://quska45.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
# 2020-01-02 code highliting on markdown.
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
comments:
  provider: disqus
disqus:
  shortname: https-quska45-github-io
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# 2022-02-27 codepen setting
codepen_username: quska45